ALTER TABLE `friends` ADD COLUMN `lost` tinyint(1) DEFAULT 0;
ALTER TABLE `friends` ADD COLUMN `errorSince` VARCHAR(1024) DEFAULT NULL;
ALTER TABLE `friends` ADD COLUMN `lostSince` VARCHAR(1024) DEFAULT NULL;
